### ISSUE TITLE
チョコレート板の板TOPにあるスレ一覧を取得する時に、コケる。

### ISSUE THREAD

**Issue by awn-git** [awn-git/Abrowzer#20]
## url

http://open.open2ch.net/chocolate/

## ログなど

ログ
```
itatop.js:79 Uncaught TypeError: Cannot read property 'length' of undefined
    at _trimThreads (file:///usr/local/Abrowzer/js/itatop.js:79:33)
    at _init (file:///usr/local/Abrowzer/js/itatop.js:30:18)
    at file:///usr/local/Abrowzer/js/itatop.js:23:5
    at file:///usr/local/Abrowzer/js/itatop.js:142:3
```

itatop.js
```
75    function _trimThreads() {
76       var d = _topThreads.children;
77        var output = [];
78
79        for (var ix = 0, len = d.length; ix < len; ix++) {
```

console.log
```
var _topThreads = document.getElementById("topThreads").childNodes[1];
_topThreadsの中身　→　<!-- スレ一覧 -->
```

## 原因
- #topThreadsにコメントノード？が入っていたため、スレ一覧が取得できなかった。
- childNodesを使ってしまったが故に起きた。
- 既存の板と新設板では構造が違うのかも？

## 対処
`var _topThreads = document.getElementById("topThreads").childNodes[1];`
↓
`var _topThreads = document.getElementById("topThreads").children[1];`
でよいのだろうか。

## その他
elementじゃなくてnodeの場合、コメントもノードに含まれるのでもしかしたらどこかでこけるかもしれない。こまったこまった。:confused:

**Comment by awn-git** [comment]
`var _topThreads = document.getElementById("topThreads").children[0];`
こうだった。
